### ISSUE TITLE
crash on negative page index

### ISSUE THREAD

**Issue by devdudeio** [Meshbits/khoji#8]
when using a negative page index khoji will crash

How to reproduce:

make GET request on `api/v1/identities/-1`

error 
```
2022/03/22 00:13:21 Failed to get identities info from DB: rethinkdb: Cannot use a negative left index on a stream. in:
r.DB("vrsctest").Table("identities").OrderBy("blockheight").Slice(-10, 0)
panic: Failed to get identities info from DB: rethinkdb: Cannot use a negative left index on a stream. in:
r.DB("vrsctest").Table("identities").OrderBy("blockheight").Slice(-10, 0)

goroutine 11 [running]:
log.Panicf({0x92c446?, 0x5?}, {0xc0000d17e0?, 0x0?, 0x0?})
        /usr/lib/go-1.18/src/log/log.go:392 +0x67
github.com/Meshbits/khoji/http.getIdentitiesSlice(0xc000284000)
        /root/khoji/http/http_routes.go:314 +0x4f8
github.com/Meshbits/khoji/http.setResponseHeader.func1(0xc000284000)
        /root/khoji/http/http_routes.go:58 +0x5b
github.com/fasthttp/router.(*Router).Handler(0xc00012bc70, 0xc000284000)
        /root/go/pkg/mod/github.com/fasthttp/router@v1.4.6/router.go:414 +0x46a
github.com/valyala/fasthttp.(*Server).serveConn(0xc0000e0fc0, {0x9e47d8?, 0xc000010430})
        /root/go/pkg/mod/github.com/valyala/fasthttp@v1.33.0/server.go:2328 +0x12c8
github.com/valyala/fasthttp.(*workerPool).workerFunc(0xc0000bd2c0, 0xc000062960)
        /root/go/pkg/mod/github.com/valyala/fasthttp@v1.33.0/workerpool.go:223 +0xa9
github.com/valyala/fasthttp.(*workerPool).getCh.func1()
        /root/go/pkg/mod/github.com/valyala/fasthttp@v1.33.0/workerpool.go:195 +0x38
created by github.com/valyala/fasthttp.(*workerPool).getCh
        /root/go/pkg/mod/github.com/valyala/fasthttp@v1.33.0/workerpool.go:194 +0x1b0
```

**Comment by satindergrewal** [comment]
thanks for reporting 👍 
will fix it soon

**Comment by satindergrewal** [comment]
@devdudeio pushed fix
